//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepTime
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string StartTime { get; set; }
        public bool IsEnded { get; set; }
        public string Duration { get; set; }
    }
}
